WebProject/WebProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
]

WebProject/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', glavna_stranica, name='glavna_stranica'),
    path('naslovna/', naslovna, name='naslovna_stranica'),
    path('tviteras/<int:pk>', tviteras, name='tviteras'),
    path('tvit/<int:pk>', tvit, name='tvit'),
    path('register/', register, name='register'),
    path('uredi_tviterasa/', uredi_tviterasa, name='uredi_tviterasa'),
]

WebProject/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Tviteras(models.Model):
    korisnik = models.OneToOneField(User, on_delete=models.CASCADE)
    ime = models.CharField(max_length=50)
    hendl = models.CharField(max_length=50)
    opis = models.CharField(max_length=255)
    lokacija = models.CharField(max_length=50)
    datum_pridruzivanja = models.DateField(auto_now_add=True)
    prati = models.ManyToManyField('self', related_name='pracen_od', symmetrical=False, blank=True)

    def __str__(self):
        return "{} ({})".format(self.hendl, self.id, self.korisnik.username)


class Lajk(models.Model):
    tvit = models.ForeignKey("Tvit", related_name='lajkovi', on_delete=models.CASCADE)
    stvorio = models.ForeignKey(User, related_name='lajkovi', on_delete=models.CASCADE)
    vrijeme_lajkanja = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "({1}) {0}".format(self.tvit.tijelo, self.id)

class Komentar(models.Model):
    tijelo = models.CharField(max_length=255)
    tvit = models.ForeignKey("Tvit", related_name='komentari', on_delete=models.CASCADE)
    stvorio = models.ForeignKey(User, related_name='komentari', on_delete=models.CASCADE)
    vrijeme_komentiranja = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('-vrijeme_komentiranja',)

    def __str__(self):
        return "{} (tvit {}) {}".format(self.stvorio.username, self.tvit.id, self.tijelo)

class Tvit(models.Model):
    tijelo = models.CharField(max_length=255)
    stvorio = models.ForeignKey(User, related_name='tvitovi', on_delete=models.CASCADE)
    tvit_lajkovi = models.ManyToManyField(User, related_name='tvit_korisnik', blank=True, through=Lajk)
    tvit_komentari = models.ManyToManyField(User, related_name='komentar_korisnik', blank=True, through=Komentar)
    vrijeme_stvaranja = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-vrijeme_stvaranja',)

    def __str__(self):
            return "{} ({}): {}".format(self.stvorio.username, self.vrijeme_stvaranja, self.tijelo[:30])


@receiver(post_save, sender=User)
def create_tviteras(sender, instance, created, **kwargs):
    if created:
        user_tviteras = Tviteras(korisnik=instance)
        user_tviteras.save()
        user_tviteras.prati.add(instance.tviteras)
        user_tviteras.save()

WebProject/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import *
from .form import *
from django.contrib.auth.decorators import login_required

# Create your views here.
def glavna_stranica(request):
    return render(request, 'base.html')


@login_required
def naslovna(request):
    tviterasi = Tviteras.objects.exclude(korisnik=request.user)
    trenutni_path = request.path
    form = TvitForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            Tvit = form.save(commit=False)
            Tvit.stvorio = request.user
            Tvit.save()
            return redirect(trenutni_path)
    return render(request, 'main/naslovna.html', {'tviterasi': tviterasi, 'form': form})


@login_required
def tviteras_list(request):
    tviterasi = Tviteras.objects.exclude(user=request.user)
    return render(request, 'main/tviteras_list.html', {'tviterasi': tviterasi})


@login_required
def tviteras(request, pk):
    tviteras = Tviteras.objects.get(pk=pk)
    if request.method == "POST":
        logirani_tviteras = request.user.tviteras
        podaci = request.POST
        radnja_pracenje = podaci.get("pracenje")

        if radnja_pracenje == "zaprati":
            logirani_tviteras.prati.add(tviteras)
        elif radnja_pracenje == "otprati":
            logirani_tviteras.prati.remove(tviteras)

        logirani_tviteras.save()
    return render(request, "main/tviteras.html", {"tviteras": tviteras})


@login_required
def tvit(request, pk):
    tvit = Tvit.objects.get(pk=pk)
    trenutni_path = request.path
    form = KomentarForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            komentar = form.save(commit=False)
            komentar.tvit = tvit
            komentar.stvorio = request.user
            komentar.save()
            return redirect(trenutni_path)

        logirani_korisnik = request.user
        podaci = request.POST
        radnja_lajkanje = podaci.get("lajkanje")

        if radnja_lajkanje == "lajk":
            tvit.tvit_lajkovi.add(logirani_korisnik)
        elif radnja_lajkanje == "dislajk":
            tvit.tvit_lajkovi.remove(logirani_korisnik)

        tvit.save()
        return redirect(trenutni_path)

    return render(request, "main/tvit.html", {"tvit": tvit, "form": form})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('main:uredi_tviterasa')
    else:
        form = UserCreationForm()

    context = {'form': form}

    return render(request, "registration/register.html", context)

@login_required
def uredi_tviterasa(request):
    tviteras = request.user.tviteras
    form = TviterasForm(request.POST or None, instance=tviteras)

    if request.method == "POST":
        if form.is_valid():
            novi_podaci = form.save(commit=False)
            novi_podaci.save()

            return redirect('main:naslovna_stranica')

    return render(request, "main/uredi_tviterasa.html", {"form": form})

WebProject/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Tviter</title>
</head>
<body>
    <section class="hero is-small is-info mb-4">
        <a href="/naslovna/">
            <div class="hero-body has-text-centered">
                <h1 class="title is-1">
                    <span class="icon"> <i class="fa-solid fa-dove"></i> </span>
                    <span class="ml-4">Tviter</span>
                </h1>
                <p class="subtitle is-4">Najaktualnija društvena mreža.</p>
            </div>
        </a>
    </section>
    <div class="container">
        <div class="columns">
            {% block content %}
                <div class="column">
                    <div class="block mt-6">
                        <div class="content">
                            <div class="buttons is-justify-content-center">
                                <a href='/accounts/login'>
                                    <button class="button is-info is-medium">
                                        <span class="icon"> <i class="fa-solid fa-address-card"></i> </span>
                                        <span> Login </span>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="block mt-6">
                        <div class="content">
                            <div class="buttons is-justify-content-center">
                                <a href="{% url 'main:register' %}">
                                    <button class="button is-info is-medium">
                                        <span class="icon"> <i class="fa-solid fa-address-card"></i> </span>
                                        <span> Registracija </span>
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock content %}
        </div>
    </div>
</body>
</html>

WebProject/main/templates/main/naslovna.html
{% extends 'base.html' %}
{% block content %}

<div class="column">
    <!-- UNOS NOVOG TVITA -->
    <div class="block mt-3 mx-3">
        <div class="box my-2 py-1 px-3">
            <article class="media">
                <div class="media-content">
                    <div class="content p-3">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="buttons mt-1 is-justify-content-center">
                                <button class="button is-info is-medium mt-1" type="submit">
                                    <span class="icon"> <i class="fa-solid fa-comment"></i> </span>
                                    <span>Tvitaj</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </article>
        </div>
    </div>

    <!-- ISPIS SVIH TVITOVA -->
    <div class="block mx-3">
        {% for praceni_tviteras in user.tviteras.prati.all %}
            {% for tvit in praceni_tviteras.korisnik.tvitovi.all %}
                <a href="{% url 'main:tvit' tvit.id %}">
                    <div class="box my-2 p-3">
                        <article class="media">
                            <div class="media-content">
                                <!-- SADRŽAJ TVITA -->
                                <div class="content">
                                    <p>
                                        <span class="title is-size-5 has-text-bold"> {{ tvit.stvorio.tviteras.ime }} </span>
                                        <span class="subtitle is-size-6 has-text-grey-light"> @{{ tvit.stvorio.tviteras.hendl }} </span>
                                        <span class="subtitle is-size-6 has-text-grey-light ml-5"> {{ tvit.vrijeme_stvaranja|timesince }}</span>
                                    </p>
                                    <p>
                                        {{ tvit.tijelo }}
                                    </p>
                                </div>
                                
                                <!-- BROJEVI LAJKOVA I KOMENTARA -->
                                <nav class="level is-mobile mt-3">
                                    <div class="level-left">
                                        <div class="buttons">
                                            <button class="button is-small is-white" disabled>
                                                <span class="icon"> <i class="fa-solid fa-heart"></i> </span>
                                                <span class="is-size-6"> {{ tvit.lajkovi.count }} </span>
                                            </button>
                                            <button class="button is-small is-white" disabled>
                                                <span class="icon"> <i class="fa-solid fa-comments"></i> </span>
                                                <span class="is-size-6"> {{ tvit.komentari.count }} </span>
                                            </button>
                                        </div>
                                    </div>
                                </nav>  
                            </div>
                        </article>
                    </div>
                </a>
            {% endfor %}
        {% endfor %}
    </div>
</div>

<!-- ISPIS SVIH TVITERAŠA -->
<div class="column is-one-quarter">
    <!-- BLOK ZA GUMBE -->
    <div class="block mt-6">
        <div class="content">
            <div class="buttons is-justify-content-center is-flex-direction-column">
                <a href="{% url 'main:tviteras' user.tviteras.id %}">
                    <button class="button is-info is-medium">
                        <span class="icon"> <i class="fa-solid fa-address-card"></i> </span>
                        <span> Moj profil </span>
                    </button>
                </a>
                <a href='/accounts/logout'>
                    <button class="button is-info is-medium">
                        <span class="icon"> <i class="fa-solid fa-address-card"></i> </span>
                        <span> Logout </span>
                    </button>
                </a>
            </div>
        </div>
    </div>

    <!-- BLOK ZA POPIS TVITERAŠA KOJE KORISNIK PRATI -->
    <div class="block mt-6">
        <h3 class="title is-4 mb-4">
            Tviteraši:
        </h3>
        <div class="content">
            {% for tviteras in tviterasi %}
                <div class="block my-2">
                    <div class="box p-3">
                        <a href="{% url 'main:tviteras' tviteras.id %}">
                            <div class="media">
                                <div class="media-content">
                                    <p>
                                        <span class="title is-5"> {{ tviteras.ime }} </span> <br>
                                        <span class="subtitle is-6"> @{{ tviteras.hendl }} </span>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

WebProject/main/templates/main/novi_tviteras.html
{% extends 'base.html' %}
{% block content %}

<div class="column m-6">
    <div class="block mt-3 mx-6">
        <div class="box my-2 py-1 px-3">
            <article class="media">
                <div class="media-content">
                    <div class="content p-3">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="buttons mt-1 is-justify-content-center">
                                <button class="button is-info is-medium mt-1" type="submit">
                                    <span class="icon"> <i class="fa-solid fa-check"></i> </span>
                                    <span>Potvrdi</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </article>
        </div>
    </div>
</div>

{% endblock content %}

WebProject/main/templates/main/tvit.html
{% extends 'base.html' %}
{% block content %}

<div class="column">
    <!-- BLOK ZA ISPIS TVITA -->
    <div class="block mt-3 mx-3">
        <div class="box my-2 p-3">
            <article class="media">
                <div class="media-content">
                    <!-- SADRŽAJ TVITA -->
                    <div class="content">
                        <p>
                            <span class="title is-size-5 has-text-bold"> {{ tvit.stvorio.tviteras.ime }} </span>
                            <span class="subtitle is-size-6 has-text-grey-light"> @{{ tvit.stvorio.tviteras.hendl }} </span>
                            <span class="subtitle is-size-6 has-text-grey-light ml-5"> {{ tvit.vrijeme_stvaranja|timesince }} </span>
                        </p>
                        <p>
                            {{ tvit.tijelo }}
                        </p>
                    </div>
                    
                    <!-- GUMBI ZA LAJKANJE I KOMENTARE -->
                    <nav class="level is-mobile mt-5">
                        <div class="level-left">
                            <form method="post">
                                {% csrf_token %}
                                <div class="buttons">
                                    {% if user in tvit.tvit_lajkovi.all  %}
                                        <button class="button is-small is-info" name="lajkanje" value="dislajk">
                                            <span class="icon"> <i class="fa-solid fa-heart-crack"></i> </span>
                                            <span class="is-size-6"> {{ tvit.lajkovi.count }} </span>
                                        </button>
                                    {% else %}
                                        <button class="button is-small is-light" name="lajkanje" value="lajk">
                                            <span class="icon"> <i class="fa-solid fa-heart"></i> </span>
                                            <span class="is-size-6"> {{ tvit.lajkovi.count }} </span>
                                        </button>
                                    {% endif %}
                                    <button class="button is-small is-white" disabled>
                                        <span class="icon"> <i class="fa-solid fa-comments"></i> </span>
                                        <span class="is-size-6"> {{ tvit.komentari.count }} </span>
                                    </button>
                                </div>
                            </form>  
                        </div>
                    </nav>  
                </div>
            </article>
        </div>
    </div>

    <!-- BLOK ZA UNOS NOVOG KOMENTARA -->
    <div class="block mt-3 mx-6">
        <div class="box my-2 py-1 px-3">
            <article class="media">
                <div class="media-content">
                    <div class="content p-3">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="buttons mt-1 is-justify-content-center">
                                <button class="button is-info is-medium mt-1" type="submit">
                                    <span class="icon"> <i class="fa-solid fa-comment"></i> </span>
                                    <span>Komentiraj</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </article>
        </div>
    </div>

    <!-- BLOKA ZA ISPIS KOMENTARA TVITA -->
    <div class="block mt-3 mx-6">
        {% for komentar in tvit.komentari.all %}
            <div class="box my-2 py-1 px-3">
                <article class="media">
                    <div class="media-content">
                        <div class="content">
                            <!-- ISPIS SADRŽAJA KOMENTARA -->
                            <div class="column">
                                <div class="columns">
                                    <div class="column">
                                        <span class="is-size-5 has-text-bold"> {{ komentar.stvorio.tviteras.ime }} </span>
                                        <span class="is-size-6 has-text-grey-light"> @{{ komentar.stvorio.tviteras.hendl }} </span>
                                        <span class="is-size-6 has-text-grey-light ml-5"> {{ komentar.vrijeme_komentiranja|timesince }} </span>

                                    </div>
                                    <div class="column">
                                        <form method="post">
                                            {% csrf_token %}
                                                <div class="buttons is-justify-content-end">
                                                {% if komentar.stvorio == user %}
                                                    <button class="button is-info is-small">
                                                        <span class="icon"> <i class="fa-solid fa-comment-slash"></i> </span>
                                                        <span>Izbriši</span>
                                                    </button>
                                                {% endif %}
                                                </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            <!-- STUPAC ZA TIJELO KOMENTARA-->
                            <div class="column">
                                    {{ komentar.tijelo }}
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

WebProject/main/templates/main/tviteras.html
{% extends 'base.html' %}

{% block content %}

<!-- STUPAC ZA INFORMACIJE O TVITERASU I POPIS NJEGOVIH TVITOVA -->
<div class="column">
    <!-- BLOK INFORMACIJA O TVITERASU -->
    <div class="block p-3">
        <div class="box">

            <div class="columns">
                <!-- IME I HENDL -->
                <div class="column">
                    <p>
                        <span class="title is-4">{{ tviteras.ime }}</span><br>
                        <span class="subtitle is-5">@{{ tviteras.hendl }}</span>
                    </p>
                </div>

                <!-- GUMBI ZA PRAĆENJE -->
                <div class="column">
                    <form method="post">
                        {% csrf_token %}
                            <div class="buttons is-justify-content-end">
                            {% if tviteras != user.tviteras %}
                                {% if tviteras in user.tviteras.prati.all %}
                                    <button class="button is-static">
                                        <span class="icon"> <i class="fa-solid fa-user-plus"></i> </span>
                                        <span>Zaprati</span>
                                    </button>
                                    <button class="button is-info" name="pracenje" value="otprati">
                                        <span class="icon"> <i class="fa-solid fa-user-minus"></i> </span>
                                        <span>Otprati</span>
                                    </button>
                                {% else %}
                                    <button class="button is-info" name="pracenje" value="zaprati">
                                        <span class="icon"> <i class="fa-solid fa-user-plus"></i> </span>
                                        <span>Zaprati</span>
                                    </button>
                                    <button class="button is-static">
                                        <span class="icon"> <i class="fa-solid fa-user-minus"></i> </span>
                                        <span>Otprati</span>
                                    </button>
                                {% endif %}
                            {% endif %}
                            </div>
                    </form>
                </div>
            </div>

            <!-- OPIS TVITERAŠA -->
            <div class="columns">
                <div class="column">
                    <span class="subtitle is-5">
                        {{ tviteras.opis }}
                    </span>
                </div>
            </div>

            <!-- LOKACIJA I DATUM PRIDRUŽIVANJA -->
            <div class="columns">
                <div class="column">
                    <span class="subtitle is-5">
                        <span class="icon"> <i class="fa-solid fa-location-pin"></i> </span>
                        <span> {{ tviteras.lokacija }} </span>

                        <span class="icon ml-5"> <i class="fa-solid fa-calendar-days"></i> </span>
                        <span> {{ tviteras.datum_pridruzivanja }} </span>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <!-- BLOK ZA LISTU TVITOVA -->
    <div class="block mt-3 mx-3">
        {% for tvit in tviteras.korisnik.tvitovi.all %}
            <a href="{% url 'main:tvit' tvit.id %}">
                <div class="box my-2 p-3">
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <span class="title is-size-5 has-text-bold"> {{ tvit.stvorio.tviteras.ime }} </span>
                                    <span class="subtitle is-size-6 has-text-grey-light"> @{{ tvit.stvorio.tviteras.hendl }} </span>
                                    <span class="subtitle is-size-6 has-text-grey-light ml-5"> {{ tvit.vrijeme_stvaranja|timesince }} </span>
                                </p>
                                <p>
                                    {{ tvit.tijelo }}
                                </p>
                            </div>
                            
                            <!-- ISPIS BROJA LAJKOVA I KOMENTARA -->
                            <nav class="level is-mobile mt-3">
                                <div class="level-left">
                                        <div class="buttons">
                                            <button class="button is-small is-white" disabled>
                                                <span class="icon"> <i class="fa-solid fa-heart"></i> </span>
                                                <span class="is-size-6"> {{ tvit.lajkovi.count }} </span>
                                            </button>
                                            <button class="button is-small is-white" disabled>
                                                <span class="icon"> <i class="fa-solid fa-comments"></i> </span>
                                                <span class="is-size-6"> {{ tvit.komentari.count }} </span>
                                            </button>
                                        </div>
                                </div>
                            </nav>  
                        </div>
                    </article>
                </div>
            </a>
        {% endfor %}
    </div>
</div>

<!-- STUPAC ZA POPIS PRATITELJA-->
<div class="column is-one-quarter">
    
    <!-- BLOK ZA GUMBE MOJ PROFIL; UREDI PROFIL; LOGOUT;  -->
    <div class="block mt-6">
        <div class="content">
            <div class="buttons is-justify-content-center is-flex-direction-column">
                {% if tviteras == user.tviteras %}
                    <a href="{% url 'main:uredi_tviterasa' %}">
                        <button class="button is-info is-medium">
                            <span class="icon"> <i class="fa-solid fa-address-card"></i> </span>
                            <span> Uredi profil </span>
                        </button>
                    </a>
                {% else %}
                    <a href="{% url 'main:tviteras' user.tviteras.id %}">
                        <button class="button is-info is-medium">
                            <span class="icon"> <i class="fa-solid fa-address-card"></i> </span>
                            <span> Moj profil </span>
                        </button>
                    </a>
                {% endif %}
                <a href='/accounts/logout'>
                    <button class="button is-info is-medium">
                        <span class="icon"> <i class="fa-solid fa-address-card"></i> </span>
                        <span> Logout </span>
                    </button>
                </a>
            </div>
        </div>
    </div>

    <!-- BLOK ZA POPIS TVITERASA KOJE KORISNIK PRATI -->
    <div class="block mt-6">
        <h3 class="title is-4 mb-4">
            {{ tviteras.prati.count }} pratim:
        </h3>
        <div class="content">
            {% for prati in tviteras.prati.all %}
                <div class="block my-2">
                    <div class="box p-3">
                        <a href="{% url 'main:tviteras' prati.id %}">
                            <div class="media">
                                <div class="media-content">
                                    <p>
                                        <span class="title is-5"> {{ prati.ime }} </span> <br>
                                        <span class="subtitle is-6"> @{{ prati.hendl }} </span>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- BLOK ZA POPIS TVITERASA KOJE PRATE KORISNIKA -->
    <div class="block mt-6">
        <h3 class="title is-4 mb-4">
            {{ tviteras.pracen_od.count }} osobe koje prate:
        </h3>
        <div class="content">
            {% for pracen_od in tviteras.pracen_od.all %}
                <div class="block my-2">
                    <div class="box p-3">
                        <a href="{% url 'main:tviteras' pracen_od.id %}">
                            <div class="media">
                                <div class="media-content">
                                    <p>
                                        <span class="title is-5"> {{ pracen_od.ime }} </span> <br>
                                        <span class="subtitle is-6"> @{{ pracen_od.hendl }} </span>
                                    </p>
                                </div>
                            </div>

                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock content %}

WebProject/main/templates/main/tviteras_list.html
{% extends 'base.html' %}
{% block content %}

<div class="column is-one-quarter">
    <!-- BLOK ZA POPIS TVITERASA KOJE KORISNIK PRATI -->
    <div class="block mt-6">
        <h3 class="title is-4 mb-4">
            Tviteraši:
        </h3>
        <div class="content">
            {% for tviteras in tviterasi %}
                <div class="block my-2">
                    <div class="box p-3">
                        <a href="{% url 'main:tviteras' prati.id %}">
                            <div class="media">
                                <div class="media-content">
                                    <p>
                                        <span class="title is-5"> {{ tviteras.ime }} </span> <br>
                                        <span class="subtitle is-6"> @{{ tviteras.hendl }} </span>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}